---

- name: install nova-compute packages
  apt:
    name: nova-compute
    state: present

- name: configure nova-compute conponents
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
  backup: yes

-name: Discover compute hosts
 shell: su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova

#-name: check nova service
# shell: nova-status upgrade check
