---

- name: Create the openstack module user
  os_user: name={{item.svc_name  password={{ item.svc_passwd }} domain=default
#  shell: openstack user create --domain default --password-prompt glance
  environment: "{{ admin_env }}" 
  with_items:
    - {{ USERS_INFO }} 

- name: Create a service for openstack modules
  os_keystone_service:
    name: {{ item.svc_name }}
    state: present
    service_type: "{{ item.svc_type }}"
    description: "{{ item.svc_desc }}"
  with_items:
    - {{ SERVICE_INFO }} 


- name: Create endpoints for modules
  os_keystone_endpoint:
    service: "{{ item[1].svc_name }}"
    endpoint_interface: {{ item[0] }}
    url: "{{ item[1].svc_url }}"
    region: RegionOne
    state: present
  with_items:
    - ['public', 'admin', 'internal']
    - {{ SERVICE_INFO }}

#- name: Create  endpoints for glance
#  os_keystone_endpoint:
#     service: glance
#     endpoint_interface: "{{ item}}"
#     url: http://controller:9292
#     region: RegionOne
#     state: present
#  with_items:
#     - public
#     - admin
#     - internal
#
#
