---
- name: Bootstrap the Identity service
  command: |
     keystone-manage bootstrap \
     --bootstrap-password {{ admin_pass }} \
     --bootstrap-admin-url http://controller:35357/v3 \
     --bootstrap-public-url http://controller:5000/v3 \
     --bootstrap-internal-url http://controller:5000/v3\
     --bootstrap-region-id RegionOne
