---

- name: Check if credential keys already exist
  stat:
    path: "{{ keystone_credential_key_repository }}/0"
  register: _credential_keys

- name: Create credential keys for Keystone
  shell: keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
  register: create_credential_keys
  when: not _credential_keys.stat.exists

- name: Ensure newest key is used for credential in Keystone
  shell: keystone-manage credential_migrate --keystone-user keystone --keystone-group keystone
  when: create_credential_keys | skipped

- name: Rotate credential keys for Keystone
  shell: keystone-manage credential_rotate --keystone-user keystone --keystone-group keystone
  when: create_credential_keys | skipped
