---

- name: install nova packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - nova-api
    - nova-conductor 
    - nova-consoleauth
    - nova-novncproxy
    - nova-scheduler
    - nova-placement-api

- name: configure nova 
  template:
    src: nova.conf.j2
    dest: /etc/nova/nova.conf
    backup: yes

- name: Populate the nova-api database
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova

- name: Register the cell0 database
  shell: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova

- name: Create the cell1 cell
  shell: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova


- name: Populate the nova database
  shell: su -s /bin/sh -c "nova-manage db sync" nova

- name: Restart the Compute services
  service:
    name: "{{ item }}"
    state: restarted

